app:
    resource: "@AppBundle/Controller/"
    type:     annotation
user_registration:
    path:     /registrar
    defaults: { _controller: AppBundle:Registration:register }
logout:
    path: /logout
